export const maps = [
  [
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
  ],
  [
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 5, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 6,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 2,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
  ],
  [
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 5, type: "", background: "", width: "50px", heith: "45px" },
    { value: 6, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 2,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 3,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
  ],
  [
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 5, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 6,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 2,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
  ],
  [
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 5, type: "", background: "", width: "50px", heith: "45px" },
    { value: 6, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 2,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 3,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
  ],
  [
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 8, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 9,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 2,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
  ],
  [
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 5, type: "", background: "", width: "50px", heith: "45px" },
    { value: 6, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 2,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 3,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
  ],
  [
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 8, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 9,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 2,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
  ],
  [
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 5, type: "", background: "", width: "50px", heith: "45px" },
    { value: 6, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 2,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 3,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
  ],
  [
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 8, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 9,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 2,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
  ],
  [
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 5, type: "", background: "", width: "50px", heith: "45px" },
    { value: 6, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 2,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 3, type: "", background: "", width: "50px", heith: "45px" },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 3,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    { value: 1, type: "", background: "", width: "50px", heith: "45px" },
    { value: 2, type: "", background: "", width: "50px", heith: "45px" },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
  ],
  [
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
    {
      value: 1,
      type: "wall",
      background: "#b35427",
      width: "50px",
      heith: "45px",
    },
  ],
];
